title: Individual Project Portfolio 2
description: XR Individual Project Portfolio
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - contributions.md
  - reflection.md
  - peer-feedback.md
  - ethics.md
